# Documentation: http://docs.travis-ci.com/user/languages/julia/

codecov: true
coveralls: true
language: julia
julia:
  - 1.5
  - nightly

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; Pkg.add("Coverage"); cd(Pkg.dir("Kinetic")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  #- julia -e 'import Pkg; Pkg.add("Coverage"); cd(Pkg.dir("Kinetic")); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
      - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - julia --project=docs/ docs/make.jl
      after_success: skip